- name: Check cluster status
  block:
    - name: "Query cluster detail"
      ansible.builtin.command: "gs_om -t status --detail"
      changed_when: false
      register: cluster_detail
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true

  rescue:
    - name: Import pre tasks
      ansible.builtin.import_tasks:
        file: pre_tasks.yml
      become_user: root

    - name: Import deploy tasks
      ansible.builtin.import_tasks:
        file: deploy/main.yml
      delegate_to: "{{ og_master }}"
      run_once: true

- name: Tasks for expansion
  when: "cluster_detail is succeeded"
  block:
    - name: Create expansion list
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups:
          - opengauss_expand
      loop: "{{ og_replicas }}"
      when: "item not in cluster_detail.stdout"
      run_once: true

    - name: Import pre tasks
      ansible.builtin.include_tasks:
        file: pre_tasks.yml
      when:
        - "groups['opengauss_expand'] is defined"
        - "inventory_hostname in groups['opengauss_expand']"

    - name: Tasks for CM cluster
      when:
        - "'cmserver' not in cluster_detail.stdout"
        - "og_cm_enabled"
      block:
        - name: Import cluster manager tasks
          ansible.builtin.import_tasks:
            file: cluster_manager.yml
          delegate_to: "{{ og_master }}"
          become_user: "{{ og_user }}"
          run_once: true

        - name: Refresh cluster status
          ansible.builtin.command:
            gs_om -t status --detail
          changed_when: false
          register: cluster_detail1
          become_user: "{{ og_user }}"
          delegate_to: "{{ og_master }}"
          run_once: true

    - name: Import cluster expand tasks
      ansible.builtin.import_tasks:
        file: cluster_expand.yml
      vars:
        og_expansion: true
      delegate_to: "{{ og_master }}"
      run_once: true
      when: "groups['opengauss_expand'] is defined"
