- name: Check cluster status
  block:
    - name: "Query cluster detail"
      ansible.builtin.command: "gs_om -t status --detail"
      changed_when: false
      register: cluster_detail
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true

  rescue:
    - name: Import pre tasks
      ansible.builtin.import_tasks:
        file: pre_tasks.yml
      become_user: root

    - name: Import deploy tasks
      ansible.builtin.import_tasks:
        file: deploy/main.yml
      delegate_to: "{{ og_master }}"
      run_once: true

    - name: Repeat tasks
      ansible.builtin.include_tasks:
        file: cluster_check.yml

- name: Mission aborted
  run_once: true
  when: "cluster_detail.stdout | regex_search(keywords, multiline=True, ignorecase=True)"
  vars:
    keywords: >-
      "(repair|down)"
  block:
    - name: Print cluster status
      ansible.builtin.debug:
        msg: |
          {{ cluster_detail.stdout_lines }}

    - name: Abort tasks when conditions matched
      ansible.builtin.fail:
        msg: |
          集群状态有异常，请检查并手动修复后，再运行 playbook。
          Cluster status is not NORMAL, pls fix them
          and run the playbook again.

- name: Tasks for expansion
  when: "cluster_detail is succeeded"
  block:
    - name: Create expansion list
      ansible.builtin.add_host:
        hostname: "{{ item }}"
        groups:
          - opengauss_expand
      loop: "{{ og_replicas }}"
      when: "item not in cluster_detail.stdout"
      run_once: true

    - name: Import pre tasks
      ansible.builtin.include_tasks:
        file: pre_tasks.yml
      when:
        - "groups['opengauss_expand'] is defined"
        - "inventory_hostname in groups['opengauss_expand']"

    - name: Tasks for CM cluster
      when:
        - "'cmserver' not in cluster_detail.stdout"
        - "og_cm_enabled"
      block:
        - name: Import cluster manager tasks
          ansible.builtin.import_tasks:
            file: cluster_manager.yml
          delegate_to: "{{ og_master }}"
          become_user: "{{ og_user }}"
          run_once: true

        - name: Refresh cluster status
          ansible.builtin.command:
            gs_om -t status --detail
          changed_when: false
          register: cluster_detail1
          become_user: "{{ og_user }}"
          delegate_to: "{{ og_master }}"
          run_once: true

    - name: Import cluster expand tasks
      ansible.builtin.import_tasks:
        file: cluster_expand.yml
      vars:
        og_expansion: true
      delegate_to: "{{ og_master }}"
      run_once: true
      when: "groups['opengauss_expand'] is defined"
