- name: Import pre tasks
  ansible.builtin.include_tasks:
    file: pre_tasks.yml
  when: "inventory_hostname in ep_nodes"

- name: Import deploy tasks
  ansible.builtin.import_tasks:
    file: deploy/main.yml
  delegate_to: "{{ og_master }}"
  run_once: true
