- name: Create {{ og_upload_path }}/cluster_config.xml
  template:
    src: "{{ item }}"
    dest: "{{ og_upload_path }}/cluster_config.xml"
    owner: "{{ og_user }}"
    group: "{{ og_group }}"
    backup: true
    lstrip_blocks: true
  with_first_found:
    - "{{ inventory_dir }}/templates/cluster_config.xml.j2"
    - "cluster_config.xml.j2"

- name: First time deploy
  block:
    - name: Starting pre install
      command: "python3 gs_preinstall -U {{ og_user }} -G {{ og_group }} -X {{ og_upload_path }}/cluster_config.xml --non-interactive"
      args:
        chdir: "{{ og_upload_path }}/script"
      changed_when: false

    - name: Deploy openGauss
      command: |
        python3 gs_install \
          -X {{ og_upload_path }}/cluster_config.xml \
          --gsinit-parameter="--pwpasswd={{ combined_vars.openGauss_db_set.root_pass }}"
      args:
        chdir: "{{ og_home }}/install/om/script"
      become_user: "{{ og_user }}"
  when: "not og_expansion"

- name: Expand cluster
  block:
    - name: Get cluster status detail
      shell: "gs_om -t status --detail"
      changed_when: false
      become_user: "{{ og_user }}"
      register: cluster_status

    - name: Starting expand
      shell: >-
        . /home/{{ og_user }}/.bashrc &&
          python3 gs_expansion -U {{ og_user }} -G {{ og_group }} -X {{ og_upload_path }}/cluster_config.xml -h {{ expansion_list }}
      args:
        chdir: "{{ og_upload_path }}/script"
      vars:
        expansion_list: >-
          {%- 
            for node in og_all_nodes
              if node not in cluster_status.stdout
          -%}
            {{ node }}{{ (loop.nextitem is defined) | ternary(',', '') }}
          {%- endfor -%}
      changed_when: false
  when: "og_expansion"