- name: Scan hosts key
  command: "ssh-keyscan -p {{ port }} {{ node }},og{{ node | ipaddr('int') }}"
  changed_when: false
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node
  vars:
    port: "{{ ansible_ssh_port | default('22') }}"
  register: known_host_keys

- name: "Update {{ og_ssh.home }}/.ssh/known_hosts"
  blockinfile:
    path: "{{ og_ssh.home }}/.ssh/known_hosts"
    owner: "{{ og_ssh.user }}"
    group: "{{ og_ssh.group }}"
    create: true
    block: |
      {% for key in (host_keys | sort) %}
      {{ key }}
      {% endfor %}
  vars:
    host_keys: "{{ known_host_keys.results | map(attribute='stdout_lines') | flatten }}"
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node
  delegate_to: "{{ node }}"