- name: "Update /root/.ssh/known_hosts"
  ansible.builtin.blockinfile:
    path: "/root/.ssh/known_hosts"
    owner: "root"
    group: "root"
    create: true
    mode: "0644"
    block: |
      {% for key in (host_keys | sort) %}
      {{ key }}
      {% endfor %}
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node
  delegate_to: "{{ node }}"

- name: "Update '{{ '/home/' + og_user + '/.ssh/known_hosts' }}'"
  ansible.builtin.blockinfile:
    path: "/home/{{ og_user }}/.ssh/known_hosts"
    owner: "{{ og_user }}"
    group: "{{ og_group }}"
    create: true
    mode: "0644"
    block: |
      {% for key in (host_keys | sort) %}
      {{ key }}
      {% endfor %}
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node
  delegate_to: "{{ node }}"
