- name: Scan hosts key
  ansible.builtin.command: "ssh-keyscan -p {{ host_port }} {{ node }},og{{ node | ipaddr('int') }}"
  changed_when: false
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node
  vars:
    host_port: "{{ ansible_ssh_port | default('22') }}"
  register: known_host_keys

- name: Config known hosts
  ansible.builtin.include_tasks: deploy/known_hosts.yml
  with_items:
    - user: root
      group: root
      home: /root
    - user: "{{ og_user }}"
      group: "{{ og_group }}"
      home: "/home/{{ og_user }}"
  loop_control:
    loop_var: og_ssh

- name: Config authorized keys
  ansible.builtin.include_tasks: deploy/add_auth.yml
  loop: "{{ og_all_nodes }}"
  loop_control:
    loop_var: node

- name: Check gs_om command
  ansible.builtin.shell: "which gs_om || echo 'not installed'"
  changed_when: false
  register: gs_com_st

- name: Upload packages
  ansible.builtin.import_tasks: deploy/upload.yml
  when: "'not installed' in gs_com_st.stdout_lines"

- name: Start install
  ansible.builtin.import_tasks: deploy/install.yml
