# - name: Expansion list
#   ansible.builtin.debug:
#     msg: "{{ groups['opengauss_expand'] }}"

- ansible.builtin.debug:
    var: cluster_detail.stdout_lines

- name: Debug
  ansible.builtin.debug:
    msg: "{{ split_line }}"
  loop: "{{ cluster_detail.stdout_lines | sort }}"
  loop_control:
    loop_var: line
  when: "'cmserver' in line"
  vars:
    split_line: "{{ line | regex_replace(' {1,}', '|') | split('|') }}"

- name: Create current cmserver list
  ansible.builtin.add_host:
    hostname: "{{ node_info[3] }}_{{ node_info[1] }}"
    groups:
      - opengauss_cm
    node_ip: "{{ node_info[2] }}"
  loop: "{{ cluster_detail.stdout_lines | sort }}"
  loop_control:
    loop_var: line
  vars:
    node_info: "{{ line | regex_replace(' {1,}', '|') | split('|') }}"
  when: "'cmserver' in line"

- name: Current cluster manager servers
  ansible.builtin.debug:
    msg: "{{ groups['opengauss_cm'] }}"
  when: "groups['opengauss_cm'] is defined"

- name: Set 'og_expand_cm_ips' facts
  ansible.builtin.set_fact:
    og_expand_cm_ips: >-
      {%- for node in (groups['opengauss_cm'] | sort) -%}
        {{ hostvars[node]['node_ip'] }}{{ (loop.nextitem is defined) | ternary(',', '') }}
      {%- endfor -%}
      {%- if groups['opengauss_expand'] is defined -%}
        {%- for node in (groups['opengauss_expand'] | sort) -%}
          ,{{ node }}
        {%- endfor -%}
      {%- endif -%}
    og_cm_names: >-
      {%- for node in (groups['opengauss_cm'] | sort) -%}
        og{{ hostvars[node]['node_ip'] | ipaddr('int') }}{{ (loop.nextitem is defined) | ternary(',', '') }}
      {%- endfor -%}
      {%- if groups['opengauss_expand'] is defined -%}
        {%- for node in (groups['opengauss_expand'] | sort) -%}
          ,og{{ node | ipaddr('int') }}
        {%- endfor -%}
      {%- endif -%}
  when: "groups['opengauss_cm'] is defined"

- name: Debug
  ansible.builtin.debug:
    msg: "{{ split_line }}"
  loop: "{{ cluster_detail.stdout_lines | sort }}"
  loop_control:
    loop_var: line
  when: "(og_data_path + '/dn') in line"
  vars:
    split_line: "{{ line | regex_replace(' {1,}', '|') | split('|') }}"

# 这里需要判断输出了多少列，因为有 CM 的集群里，不输出数据库端口的那一列。
- name: Create current data node list
  ansible.builtin.add_host:
    hostname: >-
      {%- if og_cluster_config.data_port in line -%}
        {{ node_info[4] }}_{{ node_info[1] }}_{{ node_info[7] }}
      {%- else -%}
        {{ node_info[3] }}_{{ node_info[1] }}_{{ node_info[6] }}
      {%- endif -%}
    groups:
      - opengauss_dn
    node_ip: "{{ node_info[2] }}"
    node_name: "{{ node_info[1] }}"
  loop: "{{ cluster_detail.stdout_lines | sort }}"
  loop_control:
    loop_var: line
  when: "(og_data_path + '/dn') in line"
  vars:
    node_info: "{{ line | regex_replace(' {1,}', '|') | split('|') }}"

- name: Current data nodes
  ansible.builtin.debug:
    msg: "{{ groups['opengauss_dn'] }}"
  when: "groups['opengauss_dn'] is defined"

- name: Set 'og_data_nodes' facts
  ansible.builtin.set_fact:
    og_data_nodes: >-
      {{ og_data_path }}/dn
      {%- for node in (groups['opengauss_dn'] | sort) if (hostvars[node]['node_ip'] != og_master) -%}
        ,{{ hostvars[node]['node_name'] }},{{ og_data_path }}/dn
      {%- endfor -%}
      {%- if groups['opengauss_expand'] is defined -%}
        {%- for node in (groups['opengauss_expand'] | sort)  -%}
          ,og{{ node | ipaddr('int') }},{{ og_data_path }}/dn
        {%- endfor -%}
      {%- endif -%}
    og_expansion: "{{ groups['opengauss_expand'] is defined }}"
  when:
    - "groups['opengauss_dn'] is defined"
