- name: Create /opt/software/openGauss/cluster_config.xml
  template:
    src: "{{ item }}"
    dest: "/opt/software/openGauss/cluster_config.xml"
    owner: "{{ og_user }}"
    group: "{{ og_group }}"
    backup: true
    lstrip_blocks: true
  with_first_found:
    - "{{ inventory_dir }}/templates/openGauss/cluster_config.xml.j2"
    - "cluster_config.xml.j2"

- name: Starting pre install
  command: "python3 gs_preinstall -U {{ og_user }} -G {{ og_group }} -X /opt/software/openGauss/cluster_config.xml --non-interactive"
  args:
    chdir: "/opt/software/openGauss/script"
  changed_when: false

- name: Deploy openGauss
  shell: |
    . ~/.bashrc && \
    python3 gs_install \
      -X /opt/software/openGauss/cluster_config.xml \
      --gsinit-parameter="--pwpasswd={{ combined_vars.openGauss_db_set.root_pass }}"
  args:
    chdir: "{{ og_home }}/install/om/script"
  become_user: "{{ og_user }}"
