- name: Upload and extract files
  block:
    - name: Create /opt/software/openGauss
      file:
        path: /opt/software/openGauss
        state: directory
        # owner: "{{ og_user }}"
        # group: "{{ og_group }}"
        recurse: true

    - name: "Extracting {{ og_pkg_url | basename }}"
      unarchive:
        src: "{{ playbook_dir }}/downloaded_files/{{ og_pkg_url | basename }}"
        dest: /opt/software/openGauss/
        # owner: "{{ og_user }}"
        # group: "{{ og_group }}"

    - name: "Extracting {{ og_pkg_url | basename | replace('all', 'om') }}"
      unarchive:
        remote_src: true
        src: "/opt/software/openGauss/{{ og_pkg_url | basename | replace('all', 'om') }}"
        dest: "/opt/software/openGauss/"
        # owner: "{{ og_user }}"
        # group: "{{ og_group }}"

  rescue:
    - name: "Get {{ og_pkg_url }}"
      block:
        - name: "Create {{ playbook_dir }}/downloaded_files"
          file:
            path: "{{ playbook_dir }}/downloaded_files"
            state: directory

        - name: Downloading
          get_url:
            url: "{{ og_pkg_url }}"
            dest: "{{ playbook_dir }}/downloaded_files/"
      run_once: true
      delegate_to: localhost
      become: false
    
    - include_tasks: install/upload.yml

