---
# tasks file for openGauss

- name: Tasks always run
  block:
    - name: Import vars combine tasks
      ansible.builtin.import_role:
        name: "pre_tasks"
        tasks_from: "vars_combine.yml"

    - name: Import runtime facts tasks
      ansible.builtin.import_tasks:
        file: runtime_facts.yml

    - name: Import cluster check tasks
      ansible.builtin.import_tasks:
        file: deploy/cluster_check.yml

    - name: Import cluster expand tasks
      ansible.builtin.import_tasks:
        file: deploy/cluster_expand.yml
      vars:
        cm_nodes: "{{ (groups['opengauss_cm'] is defined) | ternary(groups['opengauss_cm'], '') | sort }}"
        dn_nodes: "{{ (groups['opengauss_dn'] is defined) | ternary(groups['opengauss_dn'], '') | sort }}"
        ep_nodes: "{{ (groups['opengauss_ep'] is defined) | ternary(groups['opengauss_ep'], '') | sort }}"
        og_expansion: true
        og_cm_enabled: "{{ (groups['opengauss_cm'] is defined) | ternary(true, false) }}"
      when: "groups['opengauss_ep'] is defined"

    - name: Import cluster manager deploy
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true
      when:
        - "groups['opengauss_cm'] is not defined"
        - "og_cm_enabled"
      block:
        - name: Import cluster checking tasks
          ansible.builtin.import_tasks:
            file: deploy/cluster_check.yml

        - name: Import cluster manager deploy tasks
          ansible.builtin.import_tasks:
            file: deploy/cluster_manager.yml
          vars:
            cm_nodes: "{{ (groups['opengauss_dn'] is defined) | ternary(groups['opengauss_dn'], '') | sort }}"
            dn_nodes: "{{ (groups['opengauss_dn'] is defined) | ternary(groups['opengauss_dn'], '') | sort }}"
            ep_nodes: ""
            og_expansion: false

  always:
    - name: Import post tasks
      ansible.builtin.import_tasks:
        file: post_tasks.yml
      tags: always
