---
# tasks file for openGauss

- name: Tasks always run
  tags: always
  block:
    - name: Combine vars
      ansible.builtin.import_role:
        name: "pre-tasks"
        tasks_from: "vars_combine.yml"

    - name: Set runtime facts
      ansible.builtin.import_tasks: runtime_facts.yml

- name: Deploy cluster
  block:
    - name: Check cluster status
      ansible.builtin.command: "gs_om -t status"
      changed_when: false
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true

  rescue:
    - name: Start pre tasks
      ansible.builtin.import_tasks: pre_tasks.yml

    - name: Start deploy
      run_once: true
      delegate_to: "{{ og_master }}"
      ansible.builtin.import_tasks: deploy/main.yml

- name: Expand cluster
  block:
    - name: Check node status
      ansible.builtin.command: "gs_om -t status --detail -h {{ og_hostname }}"
      changed_when: false
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      register: check_node
      when: "inventory_hostname != og_master"

  rescue:
    - name: Hosts below will be added into cluster
      ansible.builtin.set_fact:
        og_expansion: true
      when:
        - "check_node is defined"
        - "check_node is failed"

    - name: Start pre tasks
      ansible.builtin.import_tasks: pre_tasks.yml

    - name: Start deploy
      run_once: true
      delegate_to: "{{ og_master }}"
      ansible.builtin.import_tasks: deploy/main.yml

- name: Run post tasks
  ansible.builtin.import_tasks: post_tasks.yml

- name: Generate reports
  ansible.builtin.import_tasks: report.yml
  tags:
    - never
    - report
