---
# tasks file for openGauss

- name: Tasks always run
  block:
    - name: Import vars combine tasks
      ansible.builtin.import_role:
        name: "pre_tasks"
        tasks_from: "vars_combine.yml"

    - name: Import runtime facts tasks
      ansible.builtin.import_tasks:
        file: runtime_facts.yml

    - name: Import cluster check tasks
      ansible.builtin.import_tasks:
        file: deploy/cluster_check.yml

    - name: Import cluster expand tasks
      ansible.builtin.import_tasks:
        file: deploy/cluster_expand.yml
      when: "groups['opengauss_ep'] is defined"
      become_user: root

    - name: Import cluster manager deploy tasks
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true
      ansible.builtin.import_tasks:
        file: deploy/cluster_manager.yml
      when:
        - "groups['opengauss_cm'] is not defined"
        - "groups['opengauss_dn'] | count > 2"

  always:
    - name: Import post tasks
      ansible.builtin.import_tasks:
        file: post_tasks.yml
      tags: always
