---
# tasks file for openGauss
 
- name: Tasks always run
  block:
    - name: Combine vars
      import_role:
        name: "pre-tasks"
        tasks_from: "vars_combine.yml"

    - name: Set runtime facts
      import_tasks: runtime_facts.yml
  tags: always

- block:
    - name: Check cluster status
      shell: "gs_om -t status"
      changed_when: false
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      run_once: true

  rescue:
    - name: Start pre tasks
      import_tasks: pre_tasks.yml

    - name: Start deploy
      import_tasks: deploy/main.yml
      run_once: true
      delegate_to: "{{ og_master }}"

  always:
    - name: Run post tasks
      import_tasks: post_tasks.yml

- block:
    - name: Check node status
      shell: "gs_om -t status --detail -h {{ og_hostname }}"
      changed_when: false
      become_user: "{{ og_user }}"
      delegate_to: "{{ og_master }}"
      register: check_node
      when: "inventory_hostname != og_master"

  rescue:
    - name: Cluster will be expand
      set_fact:
        og_expansion: true
      when: 
        - "check_node is failed"
        - "check_node is defined"

    - name: Start pre tasks
      import_tasks: pre_tasks.yml

    - name: Start deploy
      import_tasks: deploy/main.yml
      run_once: true
      delegate_to: "{{ og_master }}"

  always:
    - name: Run post tasks
      import_tasks: post_tasks.yml

