---
# tasks file for openGauss

- name: Tasks always run
  tags: always
  block:
    - name: Import vars combine tasks
      ansible.builtin.import_role:
        name: "pre_tasks"
        tasks_from: "vars_combine.yml"

    - name: Import runtime facts tasks
      ansible.builtin.import_tasks:
        file: runtime_facts.yml

    - name: Import cluster check tasks
      ansible.builtin.import_tasks:
        file: deploy/cluster_check.yml

  always:
    - name: Import post tasks
      ansible.builtin.import_tasks:
        file: post_tasks.yml
      tags: always
