---
# defaults file for openGauss

# 安装版本
opengauss_version: 5.0.0

# 安装目录
opengauss_home: /opt/openGauss

# 是否禁用 bash history。生产环境请设为 true，测试环境为 false。
og_disable_history: false

# 其它目录，对应 cluster_config.xml 的内容。
# 具体请看 https://docs.opengauss.org/zh/docs/{{ opengauss_version }}/docs/InstallationGuide/%E5%88%9B%E5%BB%BAXML%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6.html
opengauss_paths:
  gaussdbAppPath: "{{ opengauss_home }}/install/app"
  gaussdbLogPath: "/var/log/"
  tmpMppdbPath: "{{ opengauss_home }}/tmp"
  corePath: "{{ opengauss_home }}/corefile"
  gaussdbToolPath: "{{ opengauss_home }}/install/om"
  dataPath: "{{ opengauss_home }}/data"

# 环境设置。
opengauss_env:
  user_name: omm
  user_group: dbgrp
  user_pass: "{{ lookup('password', inventory_dir + '/credentials/opengauss_omm_pass', chars=['ascii_letters', 'digits']) | password_hash }}"
  iface_mtu: 8192
  clusterName: openGauss
  dataPortBase: 15400
  cmServerPortBase: 15300
  azName: AZ1
  swap_off: true # 关闭 swap
  syncNum: 0 # dataNode1_syncNum
  # locale: SQL_ASCII

# 数据库安装配置
opengauss_db_set:
  locale: en_US.utf8
  root_pass: "{{ lookup('password', inventory_dir + '/credentials/opengauss_root_pass', chars=['ascii_letters', 'digits'], length=16) }}"

# Sysctl 的配置，可自行扩展。
# 参考官方文档->初始化安装环境->配置操作系统参数
opengauss_sysctl:
  net.ipv4.tcp_retries1: 5
  net.ipv4.tcp_syn_retries: 5
  net.ipv4.tcp_synack_retries: 5
  # net.ipv4.tcp_fin_timeout: 60
  # net.ipv4.tcp_max_tw_buckets: 10000
  # net.ipv4.tcp_tw_reuse: 1
  # net.ipv4.tcp_tw_recycle: 1
  # net.ipv4.tcp_keepalive_time: 30
  # net.ipv4.tcp_keepalive_intvl: 30
  # net.ipv4.tcp_retries2: 12
  # net.core.wmem_max: 21299200
  # net.core.rmem_max: 21299200

# 安装包的下载链接。按 CPU 架构、操作系统及版本做区分。例如 openEuler_22 表示是针对 openEuler 22.03 版本的下载链接。
ogengauss_dl_server: https://opengauss.obs.cn-south-1.myhuaweicloud.com
opengauss_download:
  aarch64:
    openeuler_22: "{{ ogengauss_dl_server }}/{{ opengauss_version }}/arm_2203/openGauss-{{ opengauss_version }}-openEuler-64bit-all.tar.gz"
    openeuler_20: "{{ ogengauss_dl_server }}/{{ opengauss_version }}/arm/openGauss-{{ opengauss_version }}-openEuler-64bit-all.tar.gz"
  x86_64:
    openeuler_22: "{{ ogengauss_dl_server }}/{{ opengauss_version }}/x86_openEuler_2203/openGauss-{{ opengauss_version }}-openEuler-64bit-all.tar.gz"
    openeuler_20: "{{ ogengauss_dl_server }}/{{ opengauss_version }}/x86_openEuler/openGauss-{{ opengauss_version }}-openEuler-64bit-all.tar.gz"
    centos_7: "{{ ogengauss_dl_server }}/{{ opengauss_version }}/x86/openGauss-{{ opengauss_version }}-CentOS-64bit-all.tar.gz"

# 默认初始值
og_hostname: "og{{ inventory_hostname | ipaddr('int') }}"
og_all_nodes: "{{ groups['opengauss'] | sort }}"
og_master: "{{ groups['opengauss_master'] | first }}"
og_replicas: "{{ groups['opengauss_replica_nodes'] | sort }}"
og_upload_path: "/opt/software/openGauss"
og_cm_enabled: "{{ (groups['opengauss'] | count) > 2 }}"
