- name: Install dependencies
  ansible.builtin.package:
    name:
      - libnsl
      - readline-devel
      - python3-pexpect
    use: "{{ custom_pkg_mgr | default(ansible_pkg_mgr) }}"
  register: pkg_inst
  until: pkg_inst is succeeded
  retries: 3

# openGauss 5.0.0 依赖 readline 7
# openEuler 20.03 只有 readline 8
- name: Create soft link
  ansible.builtin.file:
    src: /lib64/libreadline.so.8
    dest: "/lib64/libreadline.so.7"
    state: link
