- name: Install dependencies
  ansible.builtin.package:
    name:
      - libnsl
      - readline-devel
    use: "{{ custom_pkg_mgr | default(ansible_pkg_mgr) }}"
  register: pkg_inst
  until: pkg_inst is succeeded
  retries: 3

- name: Create soft link
  ansible.builtin.file:
    src: /lib64/libreadline.so.8
    dest: "/lib64/libreadline.so.7"
    state: link
