- name: Config ssh on host
  block:
    - name: "Create path {{ og_ssh.home + '/.ssh' }}"
      ansible.builtin.file:
        path: "{{ og_ssh.home }}/.ssh"
        state: directory
        mode: "0700"
        owner: "{{ og_ssh.user }}"
        group: "{{ og_ssh.group }}"

    - name: Upload ssh keys
      ansible.builtin.copy:
        src: "{{ og_key }}"
        dest: "{{ og_ssh.home }}/.ssh/{{ og_key | basename | replace('opengauss_', '') }}"
        mode: "0400"
        owner: "{{ og_ssh.user }}"
        group: "{{ og_ssh.group }}"
        backup: true
      with_fileglob:
        - "{{ inventory_dir }}/credentials/opengauss_id*"
      loop_control:
        loop_var: og_key
        label: "{{ og_ssh.home }}/.ssh/{{ og_key | basename | replace('opengauss_', '') }}"
      register: keys_list

    - name: Failed when no keys founded
      ansible.builtin.fail:
        msg: "SSH keys not existed"
      when: "keys_list.skipped"

    - name: Permit root login
      ansible.builtin.lineinfile:
        path: /etc/ssh/sshd_config
        regexp: "^PermitRootLogin"
        line: "PermitRootLogin yes"
        backup: true

  rescue:
    - name: Generate ssh keys
      delegate_to: localhost
      become: false
      run_once: true
      block:
        - name: "Create local path 'credentials' under {{ inventory_dir }}"
          ansible.builtin.file:
            path: "{{ inventory_dir }}/credentials"
            state: directory
            mode: "0755"

        - name: Generate opengauss_id_om
          openssh_keypair:
            path: "{{ inventory_dir }}/credentials/opengauss_id_om"
            type: ed25519
            regenerate: never

        - name: Generate opengauss_id_rsa
          openssh_keypair:
            path: "{{ inventory_dir }}/credentials/opengauss_id_rsa"
            regenerate: never


    - name: Repeat tasks
      ansible.builtin.include_tasks:
        file: os/ssh.yml
