version: "3.3"

services:
  ansible:
    image: haibin.lee/ansible
    container_name: ansible-for-opengauss
    hostname: ansible-for-opengauss
    restart: always
    build:
      context: .
    working_dir: /workdir
    volumes:
      - "./inventories:/etc/ansible/inventories"
      - "../:/workdir"
      - "./ansible.cfg:/etc/ansible/ansible.cfg"
    entrypoint:
      - "tail"
      - "-f"
      - "/dev/null"
