version: "3.3"

services:
  ansible:
    image: haibin.lee/ansible
    container_name: ansible-for-opengauss
    hostname: ansible-for-opengauss
    restart: always
    build:
      context: .
    working_dir: /workdir
    volumes:
      - "../inventories:/etc/ansible/inventories"
      - "../:/workdir"
    entrypoint:
      - "crond"
      - "-f"
