# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false
  config.vm.provider :virtualbox do |vb|
    vb.memory = 4096
    vb.cpus = 2
    vb.customize [ "modifyvm", :id, "--uartmode1", "disconnected" ]
    vb.linked_clone = true
  end

  #Disabling the default /vagrant share
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # How many vm do you want?
  N = 3

  (1..N).each do |i|
  config.vm.define "opengauss#{i}" do |node|
    node.vm.box = "centos/7"
    node.vm.network :private_network, ip: "192.168.56.#{10+i}"
  end
  end
end
